services:
  - docker

script:
  - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

after_script:
  - docker-compose down

after_success:
  - curl -X POST "$DEPLOY_WEBHOOK_URL"
