version: '3'
services:
  web:
    build: .
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - SITE=${SITE}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - MONGODB_URI=${MONGODB_URI}
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - explorer:/data/db
volumes:
  explorer: {}
