version: '3'
services:
  web:
    ports:
      - '4733:3000'
    environment:
      - NODE_ENV=production
    network_mode: bridge
  mongo:
    network_mode: bridge
  imaginary:
    network_mode: bridge
