version: '3'
services:
  web:
    build: .
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - SITE=${SITE}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - MONGODB_URI=${MONGODB_URI}
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
  imaginary:
    image: h2non/imaginary:latest
    volumes:
      - images:/mnt/data
    environment:
      PORT: 9000
    command: -enable-url-source -mount /mnt/data -allowed-origins ${IMAGINARY_ALLOWED_ORIGINS} -http-cache-ttl 31556926
    ports:
      - '9000:9000'
  redis:
    image: redis
    ports:
      - '6379:6379'
volumes:
  mongo: {}
  images: {}
